### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by faktaochkunskap** [sails101/even-more-passport#13]
/Users/test/Documents/Jollyrogers/Sails/passport/config/passport.js:25
  twitter: {
  ^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/test/.node/lib/node_modules/sails/node_modules/include-all/index.js:129:29
    at Array.forEach (native)
    at requireAll (/Users/test/.node/lib/node_modules/sails/node_modules/include-all/index.js:44:9)
    at buildDictionary (/Users/test/.node/lib/node_modules/sails/node_modules/sails-build-dictionary/index.js:68:14)
    at Function.module.exports.aggregate (/Users/test/.node/lib/node_modules/sails/node_modules/sails-build-dictionary/index.js:190:9)
    at Array.loadOtherConfigFiles [as 0](/Users/test/.node/lib/node_modules/sails/lib/hooks/moduleloader/index.js:164:27)
    at /Users/test/.node/lib/node_modules/sails/node_modules/async/lib/async.js:487:38
    at Array.forEach (native)
    at _each (/Users/test/.node/lib/node_modules/sails/node_modules/async/lib/async.js:46:24)
    at Object.async.auto (/Users/test/.node/lib/node_modules/sails/node_modules/async/lib/async.js:458:9)

**Comment by faktaochkunskap** [comment]
My fault a missing "," after bearer: {
    strategy: require('passport-http-bearer').Strategy
  }
