### ISSUE TITLE
Error: Cannot find module 'passport-http-bearer'

### ISSUE THREAD

**Issue by faktaochkunskap** [sails101/even-more-passport#14]
module.js:340
    throw err;
    ^
Error: Cannot find module 'passport-http-bearer'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/test/Documents/Jollyrogers/Sails/passport/config/passport.js:22:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/test/.node/lib/node_modules/sails/node_modules/include-all/index.js:129:29
    at Array.forEach (native)
    at requireAll (/Users/test/.node/lib/node_modules/sails/node_modules/include-all/index.js:44:9)
    at buildDictionary (/Users/test/.node/lib/node_modules/sails/node_modules/sails-build-dictionary/index.js:68:14)
    at Function.module.exports.aggregate (/Users/test/.node/lib/node_modules/sails/node_modules/sails-build-dictionary/index.js:190:9)

**Comment by faktaochkunskap** [comment]
Run the following:

npm install passport-http-bearer --save

**Comment by angelxmoreno** [comment]
Please add this to the instructions

**Comment by yedhukrishnan** [comment]
passport-http-bearer is already there in `package.json`. When you do `npm install`, it will get installed automatically. @angelxmoreno Are you facing this issue now?

**Comment by angelxmoreno** [comment]
my apologies, i did not checkout the project I misread the instructions. was under the impression I could simply follow the instructions to integrate the passport into my existing project.

**Comment by yedhukrishnan** [comment]
@angelxmoreno No problem. I hope I can close this issue now. Let me know if you face any problems :)

**Comment by angelxmoreno** [comment]
no problems. please close.
