### ISSUE TITLE
Error on server startup

### ISSUE THREAD

**Issue by utkuturunc** [sails101/even-more-passport#2]
I followed the readme file but when I try sails lift I get this error. I tried copying the file straight from here.
This is the line:
      self.use(new Strategy(options, self.protocols[protocol]));

error: TypeError: undefined is not a function
    at /home/vagrant/server/api/services/passport.js:344:16
    at Array.forEach (native)
    at Authenticator.passport.loadStrategies (/home/vagrant/server/api/services/passport.js:281:27)
    at Object.module.exports.bootstrap (/home/vagrant/server/config/bootstrap.js:13:25)
    at Sails.runBootstrap (/home/vagrant/server/node_modules/sails/lib/app/private/bootstrap.js:46:27)
    at Sails.bound [as runBootstrap](/home/vagrant/server/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Sails.initialize (/home/vagrant/server/node_modules/sails/lib/app/private/initialize.js:44:9)
    at bound (/home/vagrant/server/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at /home/vagrant/server/node_modules/sails/node_modules/async/lib/async.js:551:21
    at /home/vagrant/server/node_modules/sails/node_modules/async/lib/async.js:227:13 [TypeError: undefined is not a function]
vagrant@sailsjs ~/server>

**Comment by yedhukrishnan** [comment]
Did you clone the repo? If not, what all files did you copy? I believe that you have copied all the files in `/api/services/protocols`.

**Comment by utkuturunc** [comment]
I did not clone the whole repo. Using my own sails project I used sails-generate-auth as explained in readme.md. It created the most of the files and I made necessary aditions to them again using readme. The first time I got that error I copied that file to be sure that I didn't intorudce the error while adding that else if clause.

**Comment by yedhukrishnan** [comment]
I'm looking into this issue.

By the way, Is there any link where I can see your repo?

**Comment by utkuturunc** [comment]
I just solved the issue. A previous trial with passport was causing it. Reversing changes made it. Sorry for botherin you.

**Comment by yedhukrishnan** [comment]
It's fine.. Feel free to raise an issue if you are stuck again! :)
