### ISSUE TITLE
error: Grunt :: module.js:340

### ISSUE THREAD

**Issue by faktaochkunskap** [sails101/even-more-passport#20]
Wow:

sails lift

info: Starting app...

error: Grunt :: module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/test/Documents/Jollyrogers/Sails/passport/node_modules/sails/node_modules/grunt-cli/bin/grunt'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

Error creating a connection to Postgresql using the following settings:
 { host: 'localhost',
  port: 5432,
  schema: true,
  ssl: false,
  adapter: 'sails-postgresql',
  user: 'postgres',
  password: 'postgres',
  database: 'sailsauth',
  identity: 'flashDBServer' }

---

Complete error details:
 { [error: password authentication failed for user "postgres"]
  name: 'error',
  length: 97,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '302',
  routine: 'auth_failed' }

Troubleshooting tips:

 -> You appear to be trying to use a Postgresql install on localhost. Maybe the database server isn't running, or is not installed?

 -> Is your Postgresql configuration correct?  Maybe your `poolSize` configuration is set too high? e.g. If your Postgresql database only supports 20 concurrent connections, you should make sure you have your `poolSize` set as something < 20 (see http://stackoverflow.com/a/27387928/486547). The default `poolSize` is 10. To override default settings, specify the desired properties on the relevant Postgresql "connection" config object where the host/port/database/etc. are configured. If you're using Sails, this is generally located in `config/connections.js`, or wherever your environment-specific database configuration is set.

 -> Maybe your `poolSize` configuration is set too high? e.g. If your Postgresql database only supports 20 concurrent connections, you should make sure you have your `poolSize` set as something < 20 (see http://stackoverflow.com/a/27387928/486547). The default `poolSize` is 10.

error: A hook (`orm`) failed to load!
error: error: password authentication failed for user "postgres"
    at Connection.parseE (/Users/test/Documents/Jollyrogers/Sails/passport/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:534:11)
    at Connection.parseMessage (/Users/test/Documents/Jollyrogers/Sails/passport/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (/Users/test/Documents/Jollyrogers/Sails/passport/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:528:21) { [error: password authentication failed for user "postgres"]
  name: 'error',
  length: 97,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '302',
  routine: 'auth_failed' }
error: error: password authentication failed for user "postgres"
    at Connection.parseE (/Users/test/Documents/Jollyrogers/Sails/passport/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:534:11)
    at Connection.parseMessage (/Users/test/Documents/Jollyrogers/Sails/passport/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:361:17)
    at Socket.<anonymous> (/Users/test/Documents/Jollyrogers/Sails/passport/node_modules/sails-postgresql/node_modules/pg/lib/connection.js:105:22)
    at Socket.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:764:14)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:528:21)

**Comment by faktaochkunskap** [comment]
Changed to MongoDB:

module.exports.connections = {

flashDBServer: {
    adapter: 'sails-mongo',
    host: 'localhost',
    port: 27017,
    // user: 'username',
    // password: 'password',
    database: 'sailsauth'
  }
};

Installed module:

npm install sails-mongo --save

Now it´s running, one error:

info: Starting app...

error: Grunt :: module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/test/Documents/Jollyrogers/Sails/passport/node_modules/sails/node_modules/grunt-cli/bin/grunt'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
info: 
info: 
info:    Sails              <|
info:    v0.10.5             |\
info:                       /|.\
info:                      / || \
info:                    ,'  |'  \
info:                 .-'.-==|/_--'
info:                 `--'-------' 
info:    __---___--___---___--___---___--___
info:  ____---___--___---___--___---___--___-__
info: 
info: Server lifted in`/Users/test/Documents/Jollyrogers/Sails/passport`
info: To see your app, visit http://localhost:1337
info: To shut down Sails, press <CTRL> + C at any time.

debug: --------------------------------------------------------
debug: :: Fri Mar 20 2015 20:26:01 GMT+0100 (CET)

debug: Environment : development
debug: Port        : 1337
debug: --------------------------------------------------------

**Comment by yedhukrishnan** [comment]
Can you please close all the issues that you solved? I am getting totally confused here! 

It would be nice if you spend some time with your problem before posting it here. You cannot solve all the issues at once by putting it here.
